### PR TITLE
Get xbyak4d ready for dub

### PR DESCRIPTION
**Pull request by zaydlang**
Been wanting to use this project - figured I'd clean it up and make it ready to be added as a dub package. Overall I made pretty basic changes. I moved your example files to a dedicated `examples` folder, added a `dub.json`, and cleaned up the folder structure. If you decide to merge this, let me know, and either you or I can go ahead with adding this as a dub package.

### CODE REVIEW

**Comment by GhostRain0** [comment]
Actually, given your low contribution history, and the fact that I'm excited to use this repo, I'm unsure if this will be merged, so I'm going to add a dub package using my fork. When (if) this is merged, let me know and I'll move the package repo to your original repo.

**Comment by deepprog** [comment]
Sorry for the late reply. I've been living without a computer until recently.
Thanks for the pull request.
I'll merge it.

**Comment by zaydlang** [comment]
No worries, thanks for merging! :)

Do u want me to move the dub package over to your repo?

**Comment by deepprog** [comment]
Please move the dub package to my repository.

**Comment by zaydlang** [comment]
done!

**Comment by zaydlang** [comment]
i think youll have to rename the package to xbyak rather than xbyak4d. ill just remove the package and let you add it so you have full perms

**Comment by deepprog** [comment]
Changed the package name to xbyak

**Pull request merged**
